version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airbnb-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - airbnb-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=airbnb_clone_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

  nginx:
    image: nginx:alpine
    container_name: airbnb-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - airbnb-network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: airbnb-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: airbnb_clone_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airbnb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    container_name: airbnb-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - airbnb-network

networks:
  airbnb-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  dbdata: 