version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airbnb-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - airbnb-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=airbnb_clone_db_cnld
      - DB_USERNAME=airbnb_clone_db_cnld_user
      - DB_PASSWORD=2X6drMHc0AwBx1d9toLjgkR7rNRRkRud
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_MEMORY_LIMIT=256M
      - PHP_POST_MAX_SIZE=20M
      - PHP_UPLOAD_MAX_FILESIZE=20M

  db:
    image: postgres:15
    container_name: airbnb-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: airbnb_clone_db_cnld
      POSTGRES_USER: airbnb_clone_db_cnld_user
      POSTGRES_PASSWORD: 2X6drMHc0AwBx1d9toLjgkR7rNRRkRud
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MAX_CONNECTIONS: 200
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 768MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_LARGE_OBJECTS: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - airbnb-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d airbnb_clone_db_cnld"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: airbnb-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - airbnb-network
    depends_on:
      - db

networks:
  airbnb-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data: 